server:
  port: "8080"
  mode: "debug"

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  name: "woorung_local"

jwt:
  secret: "local_secret_key"

telegram:
  token: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"

pm_agent:
  url: "http://localhost:8000"
